### ISSUE TITLE
js版本如何使用能不能说详细点啊

### ISSUE THREAD

**Issue by vinceok** [sunhaikuo/js-arouse-app#1]
let config: IAppLink = {
    // 和app协定的scheme
    schema: 'mtlf://scheme?p=home',
    // iOS下的App在appstore的地址
    appstore: '//itunes.apple.com/cn/app/%E4%BE%83%E4%BE%83%E7%8C%A9/id1267259289?mt=8',
    // 应用宝的地址
    yyb: '//a.app.qq.com/o/simple.jsp?pkgname=com.mtime.lookface&fromcase=40002'
}

像这种都不能称之为代码啊，config:IAppLink是啥写法

**Comment by sunhaikuo** [comment]
let config = {
// 和app协定的scheme
schema: 'mtlf://scheme?p=home',
// iOS下的App在appstore的地址
appstore: '//itunes.apple.com/cn/app/%E4%BE%83%E4%BE%83%E7%8C%A9/id1267259289?mt=8',
// 应用宝的地址
yyb: '//a.app.qq.com/o/simple.jsp?pkgname=com.mtime.lookface&fromcase=40002'
}

---
js直接这么用。IAppLink是Typescript的接口类型，做的是数据约束，在readme里面有写
